language: node_js

sudo: false

node_js:
    - 0.10

before_install:
    - sh bin/check_signoff.sh

install:
    - npm install -g grunt-cli
    - npm install
    - grunt jshint

script:
    - grunt test --verbose
